package misc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/tangr1/hicto/models"
)

type GetCodesReader struct {
	formats strfmt.Registry
}

func (o *GetCodesReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCodesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCodesOK creates a GetCodesOK with default headers values
func NewGetCodesOK() *GetCodesOK {
	return &GetCodesOK{}
}

/*GetCodesOK

成功获取
*/
type GetCodesOK struct {
	Payload []*models.Code
}

func (o *GetCodesOK) Error() string {
	return fmt.Sprintf("[GET /codes/][%d] getCodesOK  %+v", 200, o.Payload)
}

func (o *GetCodesOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil {
		return err
	}

	return nil
}
