package misc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/httpkit/validate"
	"github.com/go-swagger/go-swagger/strfmt"
)

type GetDocsReader struct {
	formats strfmt.Registry
}

func (o *GetDocsReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDocsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDocsOK creates a GetDocsOK with default headers values
func NewGetDocsOK() *GetDocsOK {
	return &GetDocsOK{}
}

/*GetDocsOK

成功获取
*/
type GetDocsOK struct {
	Payload GetDocsOKBodyBody
}

func (o *GetDocsOK) Error() string {
	return fmt.Sprintf("[GET /docs/][%d] getDocsOK  %+v", 200, o.Payload)
}

func (o *GetDocsOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil {
		return err
	}

	return nil
}

/*GetDocsOKBodyBody GetDocsOKBodyBody get docs o k body body

swagger:model GetDocsOKBodyBody
*/
type GetDocsOKBodyBody map[string]string

// Validate validates this get docs o k body body
func (o GetDocsOKBodyBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Required("getDocsOK", "body", o); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
