package misc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
)

// NewHeadEmailsNameParams creates a new HeadEmailsNameParams object
// with the default values initialized.
func NewHeadEmailsNameParams() *HeadEmailsNameParams {
	return &HeadEmailsNameParams{}
}

/*HeadEmailsNameParams contains all the parameters to send to the API endpoint
for the head emails name operation typically these are written to a http.Request
*/
type HeadEmailsNameParams struct {

	/*Name
	  邮箱地址

	*/
	Name string
}

// WithName adds the name to the head emails name params
func (o *HeadEmailsNameParams) WithName(name string) *HeadEmailsNameParams {
	o.Name = name
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *HeadEmailsNameParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
