package misc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
)

// NewHeadPhonesNameParams creates a new HeadPhonesNameParams object
// with the default values initialized.
func NewHeadPhonesNameParams() *HeadPhonesNameParams {
	return &HeadPhonesNameParams{}
}

/*HeadPhonesNameParams contains all the parameters to send to the API endpoint
for the head phones name operation typically these are written to a http.Request
*/
type HeadPhonesNameParams struct {

	/*Name
	  电话号码

	*/
	Name string
}

// WithName adds the name to the head phones name params
func (o *HeadPhonesNameParams) WithName(name string) *HeadPhonesNameParams {
	o.Name = name
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *HeadPhonesNameParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
