package misc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"
)

type HeadEmailsNameReader struct {
	formats strfmt.Registry
}

func (o *HeadEmailsNameReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewHeadEmailsNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewHeadEmailsNameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewHeadEmailsNameOK creates a HeadEmailsNameOK with default headers values
func NewHeadEmailsNameOK() *HeadEmailsNameOK {
	return &HeadEmailsNameOK{}
}

/*HeadEmailsNameOK

邮箱已被占用
*/
type HeadEmailsNameOK struct {
}

func (o *HeadEmailsNameOK) Error() string {
	return fmt.Sprintf("[HEAD /emails/{name}/][%d] headEmailsNameOK ", 200)
}

func (o *HeadEmailsNameOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewHeadEmailsNameNotFound creates a HeadEmailsNameNotFound with default headers values
func NewHeadEmailsNameNotFound() *HeadEmailsNameNotFound {
	return &HeadEmailsNameNotFound{}
}

/*HeadEmailsNameNotFound

邮箱未被占用
*/
type HeadEmailsNameNotFound struct {
}

func (o *HeadEmailsNameNotFound) Error() string {
	return fmt.Sprintf("[HEAD /emails/{name}/][%d] headEmailsNameNotFound ", 404)
}

func (o *HeadEmailsNameNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
