package misc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"
)

type HeadPhonesNameReader struct {
	formats strfmt.Registry
}

func (o *HeadPhonesNameReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewHeadPhonesNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewHeadPhonesNameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewHeadPhonesNameOK creates a HeadPhonesNameOK with default headers values
func NewHeadPhonesNameOK() *HeadPhonesNameOK {
	return &HeadPhonesNameOK{}
}

/*HeadPhonesNameOK

电话已被占用
*/
type HeadPhonesNameOK struct {
}

func (o *HeadPhonesNameOK) Error() string {
	return fmt.Sprintf("[HEAD /phones/{name}/][%d] headPhonesNameOK ", 200)
}

func (o *HeadPhonesNameOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewHeadPhonesNameNotFound creates a HeadPhonesNameNotFound with default headers values
func NewHeadPhonesNameNotFound() *HeadPhonesNameNotFound {
	return &HeadPhonesNameNotFound{}
}

/*HeadPhonesNameNotFound

电话未被占用
*/
type HeadPhonesNameNotFound struct {
}

func (o *HeadPhonesNameNotFound) Error() string {
	return fmt.Sprintf("[HEAD /phones/{name}/][%d] headPhonesNameNotFound ", 404)
}

func (o *HeadPhonesNameNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
