package misc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
)

// NewPostInvitesParams creates a new PostInvitesParams object
// with the default values initialized.
func NewPostInvitesParams() *PostInvitesParams {
	return &PostInvitesParams{}
}

/*PostInvitesParams contains all the parameters to send to the API endpoint
for the post invites operation typically these are written to a http.Request
*/
type PostInvitesParams struct {

	/*Body
	  邮件地址列表

	*/
	Body []string
}

// WithBody adds the body to the post invites params
func (o *PostInvitesParams) WithBody(body []string) *PostInvitesParams {
	o.Body = body
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostInvitesParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
