package misc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/tangr1/hicto/models"
)

// NewPostInvitecodesParams creates a new PostInvitecodesParams object
// with the default values initialized.
func NewPostInvitecodesParams() *PostInvitecodesParams {
	return &PostInvitecodesParams{}
}

/*PostInvitecodesParams contains all the parameters to send to the API endpoint
for the post invitecodes operation typically these are written to a http.Request
*/
type PostInvitecodesParams struct {

	/*Body*/
	Body *models.CreateInviteCodeRequest
}

// WithBody adds the body to the post invitecodes params
func (o *PostInvitecodesParams) WithBody(body *models.CreateInviteCodeRequest) *PostInvitecodesParams {
	o.Body = body
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostInvitecodesParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Body == nil {
		o.Body = new(models.CreateInviteCodeRequest)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
