package misc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"
)

type PostSendmailReader struct {
	formats strfmt.Registry
}

func (o *PostSendmailReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostSendmailOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostSendmailOK creates a PostSendmailOK with default headers values
func NewPostSendmailOK() *PostSendmailOK {
	return &PostSendmailOK{}
}

/*PostSendmailOK

成功发送
*/
type PostSendmailOK struct {
}

func (o *PostSendmailOK) Error() string {
	return fmt.Sprintf("[POST /sendmail/][%d] postSendmailOK ", 200)
}

func (o *PostSendmailOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
