package misc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"
)

type PutNotificationsMarkasreadReader struct {
	formats strfmt.Registry
}

func (o *PutNotificationsMarkasreadReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutNotificationsMarkasreadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutNotificationsMarkasreadOK creates a PutNotificationsMarkasreadOK with default headers values
func NewPutNotificationsMarkasreadOK() *PutNotificationsMarkasreadOK {
	return &PutNotificationsMarkasreadOK{}
}

/*PutNotificationsMarkasreadOK

成功更新
*/
type PutNotificationsMarkasreadOK struct {
}

func (o *PutNotificationsMarkasreadOK) Error() string {
	return fmt.Sprintf("[PUT /notifications/markasread][%d] putNotificationsMarkasreadOK ", 200)
}

func (o *PutNotificationsMarkasreadOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
