package misc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
)

// NewPutNotificationsMarkasreadParams creates a new PutNotificationsMarkasreadParams object
// with the default values initialized.
func NewPutNotificationsMarkasreadParams() *PutNotificationsMarkasreadParams {
	return &PutNotificationsMarkasreadParams{}
}

/*PutNotificationsMarkasreadParams contains all the parameters to send to the API endpoint
for the put notifications markasread operation typically these are written to a http.Request
*/
type PutNotificationsMarkasreadParams struct {

	/*Body
	  通知ID列表

	*/
	Body []int64
}

// WithBody adds the body to the put notifications markasread params
func (o *PutNotificationsMarkasreadParams) WithBody(body []int64) *PutNotificationsMarkasreadParams {
	o.Body = body
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PutNotificationsMarkasreadParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
