package reply

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
	"github.com/go-swagger/go-swagger/swag"
)

// NewGetRepliesIDParams creates a new GetRepliesIDParams object
// with the default values initialized.
func NewGetRepliesIDParams() *GetRepliesIDParams {
	return &GetRepliesIDParams{}
}

/*GetRepliesIDParams contains all the parameters to send to the API endpoint
for the get replies ID operation typically these are written to a http.Request
*/
type GetRepliesIDParams struct {

	/*ID
	  回复ID

	*/
	ID int64
}

// WithID adds the id to the get replies ID params
func (o *GetRepliesIDParams) WithID(id int64) *GetRepliesIDParams {
	o.ID = id
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetRepliesIDParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
