package reply

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/tangr1/hicto/models"
)

// NewPostRepliesParams creates a new PostRepliesParams object
// with the default values initialized.
func NewPostRepliesParams() *PostRepliesParams {
	return &PostRepliesParams{}
}

/*PostRepliesParams contains all the parameters to send to the API endpoint
for the post replies operation typically these are written to a http.Request
*/
type PostRepliesParams struct {

	/*Body*/
	Body *models.CreateTopicRequest
}

// WithBody adds the body to the post replies params
func (o *PostRepliesParams) WithBody(body *models.CreateTopicRequest) *PostRepliesParams {
	o.Body = body
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostRepliesParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Body == nil {
		o.Body = new(models.CreateTopicRequest)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
