package reply

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/tangr1/hicto/models"
)

type PostRepliesReader struct {
	formats strfmt.Registry
}

func (o *PostRepliesReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostRepliesCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostRepliesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewPostRepliesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewPostRepliesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewPostRepliesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRepliesCreated creates a PostRepliesCreated with default headers values
func NewPostRepliesCreated() *PostRepliesCreated {
	return &PostRepliesCreated{}
}

/*PostRepliesCreated

成功创建回复
*/
type PostRepliesCreated struct {
	Payload *models.Reply
}

func (o *PostRepliesCreated) Error() string {
	return fmt.Sprintf("[POST /replies/][%d] postRepliesCreated  %+v", 201, o.Payload)
}

func (o *PostRepliesCreated) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Reply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewPostRepliesBadRequest creates a PostRepliesBadRequest with default headers values
func NewPostRepliesBadRequest() *PostRepliesBadRequest {
	return &PostRepliesBadRequest{}
}

/*PostRepliesBadRequest

无效请求
*/
type PostRepliesBadRequest struct {
	Payload *models.Error
}

func (o *PostRepliesBadRequest) Error() string {
	return fmt.Sprintf("[POST /replies/][%d] postRepliesBadRequest  %+v", 400, o.Payload)
}

func (o *PostRepliesBadRequest) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewPostRepliesUnauthorized creates a PostRepliesUnauthorized with default headers values
func NewPostRepliesUnauthorized() *PostRepliesUnauthorized {
	return &PostRepliesUnauthorized{}
}

/*PostRepliesUnauthorized

未认证
*/
type PostRepliesUnauthorized struct {
	Payload *models.Error
}

func (o *PostRepliesUnauthorized) Error() string {
	return fmt.Sprintf("[POST /replies/][%d] postRepliesUnauthorized  %+v", 401, o.Payload)
}

func (o *PostRepliesUnauthorized) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewPostRepliesForbidden creates a PostRepliesForbidden with default headers values
func NewPostRepliesForbidden() *PostRepliesForbidden {
	return &PostRepliesForbidden{}
}

/*PostRepliesForbidden

无访问权限
*/
type PostRepliesForbidden struct {
	Payload *models.Error
}

func (o *PostRepliesForbidden) Error() string {
	return fmt.Sprintf("[POST /replies/][%d] postRepliesForbidden  %+v", 403, o.Payload)
}

func (o *PostRepliesForbidden) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewPostRepliesInternalServerError creates a PostRepliesInternalServerError with default headers values
func NewPostRepliesInternalServerError() *PostRepliesInternalServerError {
	return &PostRepliesInternalServerError{}
}

/*PostRepliesInternalServerError

服务端内部错误
*/
type PostRepliesInternalServerError struct {
	Payload *models.Error
}

func (o *PostRepliesInternalServerError) Error() string {
	return fmt.Sprintf("[POST /replies/][%d] postRepliesInternalServerError  %+v", 500, o.Payload)
}

func (o *PostRepliesInternalServerError) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}
