package reply

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
	"github.com/go-swagger/go-swagger/swag"

	"github.com/tangr1/hicto/models"
)

// NewPutRepliesIDParams creates a new PutRepliesIDParams object
// with the default values initialized.
func NewPutRepliesIDParams() *PutRepliesIDParams {
	return &PutRepliesIDParams{}
}

/*PutRepliesIDParams contains all the parameters to send to the API endpoint
for the put replies ID operation typically these are written to a http.Request
*/
type PutRepliesIDParams struct {

	/*Body*/
	Body models.Reply
	/*ID
	  回复ID

	*/
	ID int64
}

// WithBody adds the body to the put replies ID params
func (o *PutRepliesIDParams) WithBody(body models.Reply) *PutRepliesIDParams {
	o.Body = body
	return o
}

// WithID adds the id to the put replies ID params
func (o *PutRepliesIDParams) WithID(id int64) *PutRepliesIDParams {
	o.ID = id
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PutRepliesIDParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
