package expert

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/tangr1/hicto/models"
)

type GetExpertsReader struct {
	formats strfmt.Registry
}

func (o *GetExpertsReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetExpertsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetExpertsOK creates a GetExpertsOK with default headers values
func NewGetExpertsOK() *GetExpertsOK {
	return &GetExpertsOK{}
}

/*GetExpertsOK

专家列表
*/
type GetExpertsOK struct {
	Payload *models.ExpertPageableResult
}

func (o *GetExpertsOK) Error() string {
	return fmt.Sprintf("[GET /experts/][%d] getExpertsOK  %+v", 200, o.Payload)
}

func (o *GetExpertsOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExpertPageableResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}
