package comment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/tangr1/hicto/models"
)

type GetCommentsIDReader struct {
	formats strfmt.Registry
}

func (o *GetCommentsIDReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCommentsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetCommentsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCommentsIDOK creates a GetCommentsIDOK with default headers values
func NewGetCommentsIDOK() *GetCommentsIDOK {
	return &GetCommentsIDOK{}
}

/*GetCommentsIDOK

成功查询评论
*/
type GetCommentsIDOK struct {
	Payload *models.Comment
}

func (o *GetCommentsIDOK) Error() string {
	return fmt.Sprintf("[GET /comments/{id}/][%d] getCommentsIdOK  %+v", 200, o.Payload)
}

func (o *GetCommentsIDOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Comment)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewGetCommentsIDNotFound creates a GetCommentsIDNotFound with default headers values
func NewGetCommentsIDNotFound() *GetCommentsIDNotFound {
	return &GetCommentsIDNotFound{}
}

/*GetCommentsIDNotFound

没找到指定对象
*/
type GetCommentsIDNotFound struct {
	Payload *models.Error
}

func (o *GetCommentsIDNotFound) Error() string {
	return fmt.Sprintf("[GET /comments/{id}/][%d] getCommentsIdNotFound  %+v", 404, o.Payload)
}

func (o *GetCommentsIDNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}
