package comment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/tangr1/hicto/models"
)

type GetCommentsReader struct {
	formats strfmt.Registry
}

func (o *GetCommentsReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCommentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCommentsOK creates a GetCommentsOK with default headers values
func NewGetCommentsOK() *GetCommentsOK {
	return &GetCommentsOK{}
}

/*GetCommentsOK

评论列表
*/
type GetCommentsOK struct {
	Payload *models.CommentPageableResult
}

func (o *GetCommentsOK) Error() string {
	return fmt.Sprintf("[GET /comments/][%d] getCommentsOK  %+v", 200, o.Payload)
}

func (o *GetCommentsOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommentPageableResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}
