package comment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
	"github.com/go-swagger/go-swagger/swag"

	"github.com/tangr1/hicto/models"
)

// NewPutCommentsIDParams creates a new PutCommentsIDParams object
// with the default values initialized.
func NewPutCommentsIDParams() *PutCommentsIDParams {
	return &PutCommentsIDParams{}
}

/*PutCommentsIDParams contains all the parameters to send to the API endpoint
for the put comments ID operation typically these are written to a http.Request
*/
type PutCommentsIDParams struct {

	/*Body*/
	Body *models.UpdateCommentRequest
	/*ID
	  评论ID

	*/
	ID int64
}

// WithBody adds the body to the put comments ID params
func (o *PutCommentsIDParams) WithBody(body *models.UpdateCommentRequest) *PutCommentsIDParams {
	o.Body = body
	return o
}

// WithID adds the id to the put comments ID params
func (o *PutCommentsIDParams) WithID(id int64) *PutCommentsIDParams {
	o.ID = id
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PutCommentsIDParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Body == nil {
		o.Body = new(models.UpdateCommentRequest)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
