package employee

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
	"github.com/go-swagger/go-swagger/swag"
)

// NewDeleteEmployeesIDParams creates a new DeleteEmployeesIDParams object
// with the default values initialized.
func NewDeleteEmployeesIDParams() *DeleteEmployeesIDParams {
	return &DeleteEmployeesIDParams{}
}

/*DeleteEmployeesIDParams contains all the parameters to send to the API endpoint
for the delete employees ID operation typically these are written to a http.Request
*/
type DeleteEmployeesIDParams struct {

	/*ID
	  创业公司员工ID

	*/
	ID int64
}

// WithID adds the id to the delete employees ID params
func (o *DeleteEmployeesIDParams) WithID(id int64) *DeleteEmployeesIDParams {
	o.ID = id
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteEmployeesIDParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
