package employee

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
	"github.com/go-swagger/go-swagger/swag"
)

// NewGetEmployeesParams creates a new GetEmployeesParams object
// with the default values initialized.
func NewGetEmployeesParams() *GetEmployeesParams {
	return &GetEmployeesParams{}
}

/*GetEmployeesParams contains all the parameters to send to the API endpoint
for the get employees operation typically these are written to a http.Request
*/
type GetEmployeesParams struct {

	/*Page
	  当前页码

	*/
	Page int64
	/*Pagesize
	  每页项数

	*/
	Pagesize int64
	/*Startupid
	  创业公司ID

	*/
	Startupid int64
}

// WithPage adds the page to the get employees params
func (o *GetEmployeesParams) WithPage(page int64) *GetEmployeesParams {
	o.Page = page
	return o
}

// WithPagesize adds the pagesize to the get employees params
func (o *GetEmployeesParams) WithPagesize(pagesize int64) *GetEmployeesParams {
	o.Pagesize = pagesize
	return o
}

// WithStartupid adds the startupid to the get employees params
func (o *GetEmployeesParams) WithStartupid(startupid int64) *GetEmployeesParams {
	o.Startupid = startupid
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetEmployeesParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param page
	if err := r.SetPathParam("page", swag.FormatInt64(o.Page)); err != nil {
		return err
	}

	// path param pagesize
	if err := r.SetPathParam("pagesize", swag.FormatInt64(o.Pagesize)); err != nil {
		return err
	}

	// path param startupid
	if err := r.SetPathParam("startupid", swag.FormatInt64(o.Startupid)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
