package employee

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/tangr1/hicto/models"
)

type GetEmployeesIDReader struct {
	formats strfmt.Registry
}

func (o *GetEmployeesIDReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetEmployeesIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetEmployeesIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetEmployeesIDOK creates a GetEmployeesIDOK with default headers values
func NewGetEmployeesIDOK() *GetEmployeesIDOK {
	return &GetEmployeesIDOK{}
}

/*GetEmployeesIDOK

成功查询创业公司员工
*/
type GetEmployeesIDOK struct {
	Payload *models.Employee
}

func (o *GetEmployeesIDOK) Error() string {
	return fmt.Sprintf("[GET /employees/{id}/][%d] getEmployeesIdOK  %+v", 200, o.Payload)
}

func (o *GetEmployeesIDOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Employee)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewGetEmployeesIDNotFound creates a GetEmployeesIDNotFound with default headers values
func NewGetEmployeesIDNotFound() *GetEmployeesIDNotFound {
	return &GetEmployeesIDNotFound{}
}

/*GetEmployeesIDNotFound

没找到指定对象
*/
type GetEmployeesIDNotFound struct {
	Payload *models.Error
}

func (o *GetEmployeesIDNotFound) Error() string {
	return fmt.Sprintf("[GET /employees/{id}/][%d] getEmployeesIdNotFound  %+v", 404, o.Payload)
}

func (o *GetEmployeesIDNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}
