package employee

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/tangr1/hicto/models"
)

type GetEmployeesReader struct {
	formats strfmt.Registry
}

func (o *GetEmployeesReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetEmployeesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetEmployeesOK creates a GetEmployeesOK with default headers values
func NewGetEmployeesOK() *GetEmployeesOK {
	return &GetEmployeesOK{}
}

/*GetEmployeesOK

员工列表
*/
type GetEmployeesOK struct {
	Payload *models.EmployeePageableResult
}

func (o *GetEmployeesOK) Error() string {
	return fmt.Sprintf("[GET /employees/][%d] getEmployeesOK  %+v", 200, o.Payload)
}

func (o *GetEmployeesOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EmployeePageableResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}
