package employee

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
	"github.com/go-swagger/go-swagger/swag"
)

// NewGetEmployeesParams creates a new GetEmployeesParams object
// with the default values initialized.
func NewGetEmployeesParams() *GetEmployeesParams {
	return &GetEmployeesParams{}
}

/*GetEmployeesParams contains all the parameters to send to the API endpoint
for the get employees operation typically these are written to a http.Request
*/
type GetEmployeesParams struct {

	/*Page
	  当前页码

	*/
	Page int64
	/*Pagesize
	  每页项数

	*/
	Pagesize int64
	/*Startupid
	  创业公司ID

	*/
	Startupid int64
}

// WithPage adds the page to the get employees params
func (o *GetEmployeesParams) WithPage(page int64) *GetEmployeesParams {
	o.Page = page
	return o
}

// WithPagesize adds the pagesize to the get employees params
func (o *GetEmployeesParams) WithPagesize(pagesize int64) *GetEmployeesParams {
	o.Pagesize = pagesize
	return o
}

// WithStartupid adds the startupid to the get employees params
func (o *GetEmployeesParams) WithStartupid(startupid int64) *GetEmployeesParams {
	o.Startupid = startupid
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetEmployeesParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// query param page
	qrPage := o.Page
	qPage := swag.FormatInt64(qrPage)
	if qPage != "" && qPage != "-1" {
		if err := r.SetQueryParam("page", qPage); err != nil {
			return err
		}
	}

	// query array param page

	// query param pagesize
	qrPagesize := o.Pagesize
	qPagesize := swag.FormatInt64(qrPagesize)
	if qPagesize != "" && qPagesize != "-1" {
		if err := r.SetQueryParam("pagesize", qPagesize); err != nil {
			return err
		}
	}

	// query array param pagesize

	// query param startupid
	qrStartupid := o.Startupid
	qStartupid := swag.FormatInt64(qrStartupid)
	if qStartupid != "" && qStartupid != "-1" {
		if err := r.SetQueryParam("startupid", qStartupid); err != nil {
			return err
		}
	}

	// query array param startupid

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
