package employee

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/tangr1/hicto/models"
)

type PostEmployeesReader struct {
	formats strfmt.Registry
}

func (o *PostEmployeesReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostEmployeesCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostEmployeesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewPostEmployeesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewPostEmployeesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewPostEmployeesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostEmployeesCreated creates a PostEmployeesCreated with default headers values
func NewPostEmployeesCreated() *PostEmployeesCreated {
	return &PostEmployeesCreated{}
}

/*PostEmployeesCreated

成功创建创业公司员工
*/
type PostEmployeesCreated struct {
	Payload *models.Employee
}

func (o *PostEmployeesCreated) Error() string {
	return fmt.Sprintf("[POST /employees/][%d] postEmployeesCreated  %+v", 201, o.Payload)
}

func (o *PostEmployeesCreated) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Employee)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewPostEmployeesBadRequest creates a PostEmployeesBadRequest with default headers values
func NewPostEmployeesBadRequest() *PostEmployeesBadRequest {
	return &PostEmployeesBadRequest{}
}

/*PostEmployeesBadRequest

无效请求
*/
type PostEmployeesBadRequest struct {
	Payload *models.Error
}

func (o *PostEmployeesBadRequest) Error() string {
	return fmt.Sprintf("[POST /employees/][%d] postEmployeesBadRequest  %+v", 400, o.Payload)
}

func (o *PostEmployeesBadRequest) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewPostEmployeesUnauthorized creates a PostEmployeesUnauthorized with default headers values
func NewPostEmployeesUnauthorized() *PostEmployeesUnauthorized {
	return &PostEmployeesUnauthorized{}
}

/*PostEmployeesUnauthorized

未认证
*/
type PostEmployeesUnauthorized struct {
	Payload *models.Error
}

func (o *PostEmployeesUnauthorized) Error() string {
	return fmt.Sprintf("[POST /employees/][%d] postEmployeesUnauthorized  %+v", 401, o.Payload)
}

func (o *PostEmployeesUnauthorized) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewPostEmployeesForbidden creates a PostEmployeesForbidden with default headers values
func NewPostEmployeesForbidden() *PostEmployeesForbidden {
	return &PostEmployeesForbidden{}
}

/*PostEmployeesForbidden

无访问权限
*/
type PostEmployeesForbidden struct {
	Payload *models.Error
}

func (o *PostEmployeesForbidden) Error() string {
	return fmt.Sprintf("[POST /employees/][%d] postEmployeesForbidden  %+v", 403, o.Payload)
}

func (o *PostEmployeesForbidden) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewPostEmployeesInternalServerError creates a PostEmployeesInternalServerError with default headers values
func NewPostEmployeesInternalServerError() *PostEmployeesInternalServerError {
	return &PostEmployeesInternalServerError{}
}

/*PostEmployeesInternalServerError

服务端内部错误
*/
type PostEmployeesInternalServerError struct {
	Payload *models.Error
}

func (o *PostEmployeesInternalServerError) Error() string {
	return fmt.Sprintf("[POST /employees/][%d] postEmployeesInternalServerError  %+v", 500, o.Payload)
}

func (o *PostEmployeesInternalServerError) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}
