package security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/tangr1/hicto/models"
)

// NewPostAuthResetParams creates a new PostAuthResetParams object
// with the default values initialized.
func NewPostAuthResetParams() *PostAuthResetParams {
	return &PostAuthResetParams{}
}

/*PostAuthResetParams contains all the parameters to send to the API endpoint
for the post auth reset operation typically these are written to a http.Request
*/
type PostAuthResetParams struct {

	/*Body
	  新密码

	*/
	Body models.ResetPasswordRequest
}

// WithBody adds the body to the post auth reset params
func (o *PostAuthResetParams) WithBody(body models.ResetPasswordRequest) *PostAuthResetParams {
	o.Body = body
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostAuthResetParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
