package security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/tangr1/hicto/models"
)

type PostEmployeeLoginReader struct {
	formats strfmt.Registry
}

func (o *PostEmployeeLoginReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostEmployeeLoginOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostEmployeeLoginBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewPostEmployeeLoginUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostEmployeeLoginOK creates a PostEmployeeLoginOK with default headers values
func NewPostEmployeeLoginOK() *PostEmployeeLoginOK {
	return &PostEmployeeLoginOK{}
}

/*PostEmployeeLoginOK

成功获取token
*/
type PostEmployeeLoginOK struct {
	Payload *models.AuthenticationResponse
}

func (o *PostEmployeeLoginOK) Error() string {
	return fmt.Sprintf("[POST /employee/login/][%d] postEmployeeLoginOK  %+v", 200, o.Payload)
}

func (o *PostEmployeeLoginOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthenticationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewPostEmployeeLoginBadRequest creates a PostEmployeeLoginBadRequest with default headers values
func NewPostEmployeeLoginBadRequest() *PostEmployeeLoginBadRequest {
	return &PostEmployeeLoginBadRequest{}
}

/*PostEmployeeLoginBadRequest

请求无效
*/
type PostEmployeeLoginBadRequest struct {
	Payload *models.Error
}

func (o *PostEmployeeLoginBadRequest) Error() string {
	return fmt.Sprintf("[POST /employee/login/][%d] postEmployeeLoginBadRequest  %+v", 400, o.Payload)
}

func (o *PostEmployeeLoginBadRequest) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewPostEmployeeLoginUnauthorized creates a PostEmployeeLoginUnauthorized with default headers values
func NewPostEmployeeLoginUnauthorized() *PostEmployeeLoginUnauthorized {
	return &PostEmployeeLoginUnauthorized{}
}

/*PostEmployeeLoginUnauthorized

用户名或密码有问题
*/
type PostEmployeeLoginUnauthorized struct {
	Payload *models.Error
}

func (o *PostEmployeeLoginUnauthorized) Error() string {
	return fmt.Sprintf("[POST /employee/login/][%d] postEmployeeLoginUnauthorized  %+v", 401, o.Payload)
}

func (o *PostEmployeeLoginUnauthorized) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}
