package security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/tangr1/hicto/models"
)

// NewPostAuthForgotParams creates a new PostAuthForgotParams object
// with the default values initialized.
func NewPostAuthForgotParams() *PostAuthForgotParams {
	return &PostAuthForgotParams{}
}

/*PostAuthForgotParams contains all the parameters to send to the API endpoint
for the post auth forgot operation typically these are written to a http.Request
*/
type PostAuthForgotParams struct {

	/*Body
	  邮箱地址

	*/
	Body models.ForgotPasswordRequest
}

// WithBody adds the body to the post auth forgot params
func (o *PostAuthForgotParams) WithBody(body models.ForgotPasswordRequest) *PostAuthForgotParams {
	o.Body = body
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostAuthForgotParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
