package security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/tangr1/hicto/models"
)

type PostOssSignatureReader struct {
	formats strfmt.Registry
}

func (o *PostOssSignatureReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostOssSignatureOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostOssSignatureBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostOssSignatureOK creates a PostOssSignatureOK with default headers values
func NewPostOssSignatureOK() *PostOssSignatureOK {
	return &PostOssSignatureOK{}
}

/*PostOssSignatureOK

成功获取
*/
type PostOssSignatureOK struct {
	Payload *models.OssSignatureResponse
}

func (o *PostOssSignatureOK) Error() string {
	return fmt.Sprintf("[POST /oss/signature][%d] postOssSignatureOK  %+v", 200, o.Payload)
}

func (o *PostOssSignatureOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OssSignatureResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewPostOssSignatureBadRequest creates a PostOssSignatureBadRequest with default headers values
func NewPostOssSignatureBadRequest() *PostOssSignatureBadRequest {
	return &PostOssSignatureBadRequest{}
}

/*PostOssSignatureBadRequest

参数无效
*/
type PostOssSignatureBadRequest struct {
	Payload *models.Error
}

func (o *PostOssSignatureBadRequest) Error() string {
	return fmt.Sprintf("[POST /oss/signature][%d] postOssSignatureBadRequest  %+v", 400, o.Payload)
}

func (o *PostOssSignatureBadRequest) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}
