package security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"
)

type PostAuthForgotReader struct {
	formats strfmt.Registry
}

func (o *PostAuthForgotReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostAuthForgotOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostAuthForgotOK creates a PostAuthForgotOK with default headers values
func NewPostAuthForgotOK() *PostAuthForgotOK {
	return &PostAuthForgotOK{}
}

/*PostAuthForgotOK

生成含token的短链并发送给用户邮件
*/
type PostAuthForgotOK struct {
}

func (o *PostAuthForgotOK) Error() string {
	return fmt.Sprintf("[POST /auth/forgot][%d] postAuthForgotOK ", 200)
}

func (o *PostAuthForgotOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
