package security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/tangr1/hicto/models"
)

// NewPostCsecCheckParams creates a new PostCsecCheckParams object
// with the default values initialized.
func NewPostCsecCheckParams() *PostCsecCheckParams {
	return &PostCsecCheckParams{}
}

/*PostCsecCheckParams contains all the parameters to send to the API endpoint
for the post csec check operation typically these are written to a http.Request
*/
type PostCsecCheckParams struct {

	/*Body
	  CSEC请求

	*/
	Body models.CsecCheckRequest
}

// WithBody adds the body to the post csec check params
func (o *PostCsecCheckParams) WithBody(body models.CsecCheckRequest) *PostCsecCheckParams {
	o.Body = body
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostCsecCheckParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
