package security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/tangr1/hicto/models"
)

// NewPostEmployeeLoginParams creates a new PostEmployeeLoginParams object
// with the default values initialized.
func NewPostEmployeeLoginParams() *PostEmployeeLoginParams {
	return &PostEmployeeLoginParams{}
}

/*PostEmployeeLoginParams contains all the parameters to send to the API endpoint
for the post employee login operation typically these are written to a http.Request
*/
type PostEmployeeLoginParams struct {

	/*Body*/
	Body *models.AuthenticationRequest
}

// WithBody adds the body to the post employee login params
func (o *PostEmployeeLoginParams) WithBody(body *models.AuthenticationRequest) *PostEmployeeLoginParams {
	o.Body = body
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostEmployeeLoginParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Body == nil {
		o.Body = new(models.AuthenticationRequest)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
