package security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/tangr1/hicto/models"
)

type PostAuthLogoutReader struct {
	formats strfmt.Registry
}

func (o *PostAuthLogoutReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostAuthLogoutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostAuthLogoutBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostAuthLogoutOK creates a PostAuthLogoutOK with default headers values
func NewPostAuthLogoutOK() *PostAuthLogoutOK {
	return &PostAuthLogoutOK{}
}

/*PostAuthLogoutOK

成功登出
*/
type PostAuthLogoutOK struct {
}

func (o *PostAuthLogoutOK) Error() string {
	return fmt.Sprintf("[POST /auth/logout/][%d] postAuthLogoutOK ", 200)
}

func (o *PostAuthLogoutOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAuthLogoutBadRequest creates a PostAuthLogoutBadRequest with default headers values
func NewPostAuthLogoutBadRequest() *PostAuthLogoutBadRequest {
	return &PostAuthLogoutBadRequest{}
}

/*PostAuthLogoutBadRequest

token无效
*/
type PostAuthLogoutBadRequest struct {
	Payload *models.Error
}

func (o *PostAuthLogoutBadRequest) Error() string {
	return fmt.Sprintf("[POST /auth/logout/][%d] postAuthLogoutBadRequest  %+v", 400, o.Payload)
}

func (o *PostAuthLogoutBadRequest) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}
