package startup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
	"github.com/go-swagger/go-swagger/swag"

	"github.com/tangr1/hicto/models"
)

// NewPutStartupsIDParams creates a new PutStartupsIDParams object
// with the default values initialized.
func NewPutStartupsIDParams() *PutStartupsIDParams {
	return &PutStartupsIDParams{}
}

/*PutStartupsIDParams contains all the parameters to send to the API endpoint
for the put startups ID operation typically these are written to a http.Request
*/
type PutStartupsIDParams struct {

	/*Body*/
	Body *models.UpdateStartupRequest
	/*ID
	  创业公司ID

	*/
	ID int64
}

// WithBody adds the body to the put startups ID params
func (o *PutStartupsIDParams) WithBody(body *models.UpdateStartupRequest) *PutStartupsIDParams {
	o.Body = body
	return o
}

// WithID adds the id to the put startups ID params
func (o *PutStartupsIDParams) WithID(id int64) *PutStartupsIDParams {
	o.ID = id
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PutStartupsIDParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Body == nil {
		o.Body = new(models.UpdateStartupRequest)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
