package topic

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/tangr1/hicto/models"
)

type GetTopicsIDReader struct {
	formats strfmt.Registry
}

func (o *GetTopicsIDReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetTopicsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetTopicsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetTopicsIDOK creates a GetTopicsIDOK with default headers values
func NewGetTopicsIDOK() *GetTopicsIDOK {
	return &GetTopicsIDOK{}
}

/*GetTopicsIDOK

成功查询主题
*/
type GetTopicsIDOK struct {
	Payload *models.Topic
}

func (o *GetTopicsIDOK) Error() string {
	return fmt.Sprintf("[GET /topics/{id}/][%d] getTopicsIdOK  %+v", 200, o.Payload)
}

func (o *GetTopicsIDOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Topic)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewGetTopicsIDNotFound creates a GetTopicsIDNotFound with default headers values
func NewGetTopicsIDNotFound() *GetTopicsIDNotFound {
	return &GetTopicsIDNotFound{}
}

/*GetTopicsIDNotFound

没找到指定对象
*/
type GetTopicsIDNotFound struct {
	Payload *models.Error
}

func (o *GetTopicsIDNotFound) Error() string {
	return fmt.Sprintf("[GET /topics/{id}/][%d] getTopicsIdNotFound  %+v", 404, o.Payload)
}

func (o *GetTopicsIDNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}
