package topic

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/tangr1/hicto/models"
)

type GetTopicsReader struct {
	formats strfmt.Registry
}

func (o *GetTopicsReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetTopicsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetTopicsOK creates a GetTopicsOK with default headers values
func NewGetTopicsOK() *GetTopicsOK {
	return &GetTopicsOK{}
}

/*GetTopicsOK

主题列表
*/
type GetTopicsOK struct {
	Payload *models.TopicPageableResult
}

func (o *GetTopicsOK) Error() string {
	return fmt.Sprintf("[GET /topics/][%d] getTopicsOK  %+v", 200, o.Payload)
}

func (o *GetTopicsOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TopicPageableResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}
