package topic

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
	"github.com/go-swagger/go-swagger/swag"

	"github.com/tangr1/hicto/models"
)

// NewPutTopicsIDParams creates a new PutTopicsIDParams object
// with the default values initialized.
func NewPutTopicsIDParams() *PutTopicsIDParams {
	return &PutTopicsIDParams{}
}

/*PutTopicsIDParams contains all the parameters to send to the API endpoint
for the put topics ID operation typically these are written to a http.Request
*/
type PutTopicsIDParams struct {

	/*Body*/
	Body *models.UpdateTopicRequest
	/*ID
	  主题ID

	*/
	ID int64
}

// WithBody adds the body to the put topics ID params
func (o *PutTopicsIDParams) WithBody(body *models.UpdateTopicRequest) *PutTopicsIDParams {
	o.Body = body
	return o
}

// WithID adds the id to the put topics ID params
func (o *PutTopicsIDParams) WithID(id int64) *PutTopicsIDParams {
	o.ID = id
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PutTopicsIDParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Body == nil {
		o.Body = new(models.UpdateTopicRequest)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
