package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*表示认证响应

swagger:model AuthenticationResponse
*/
type AuthenticationResponse struct {

	/* 若为创业公司员工, 则返回此项
	 */
	Employee Employee `json:"employee,omitempty"`

	/* 若为专家, 则返回此项
	 */
	Expert Expert `json:"expert,omitempty"`

	/* token失效时间
	 */
	ExpiresIn int64 `json:"expiresIn,omitempty"`

	/* 服务器当前时间
	 */
	ServerTime int64 `json:"serverTime,omitempty"`

	/* 是否为创业公司员工
	 */
	Startup *bool `json:"startup,omitempty"`

	/* 访问token
	 */
	Token string `json:"token,omitempty"`
}

// Validate validates this authentication response
func (m *AuthenticationResponse) Validate(formats strfmt.Registry) error {
	return nil
}
