package models

import (
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
)

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*表示评论资源

swagger:model Comment
*/
type Comment struct {
	Post

	/* 评论针对的评论ID
	 */
	ReferCommentID int64 `json:"referCommentId,omitempty"`

	/* 评论回复的ID
	 */
	ReplyID int64 `json:"replyId,omitempty"`

	/* 评论针对的作者
	 */
	ReplyTo *Author `json:"replyTo,omitempty"`

	/* 评论主题的ID
	 */
	TopicID int64 `json:"topicId,omitempty"`
}

// Validate validates this comment
func (m *Comment) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.Post.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
