package models

import (
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
)

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*表示邀请码资源

swagger:model InviteCode
*/
type InviteCode struct {
	Resource

	/* 邀请码
	 */
	Code string `json:"code,omitempty"`

	/* InviterID inviter id
	 */
	InviterID int64 `json:"inviterId,omitempty"`

	/* 可用次数, 默认为1
	 */
	Quota int32 `json:"quota,omitempty"`

	/* 创业公司ID，如是专家邀请码，则无此项
	 */
	StartupID int64 `json:"startupId,omitempty"`

	/* 已用次数
	 */
	Used int32 `json:"used,omitempty"`
}

// Validate validates this invite code
func (m *InviteCode) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.Resource.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
