package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*表示通知资源

swagger:model Notification
*/
type Notification struct {

	/* 发布者
	 */
	Author *Author `json:"author,omitempty"`

	/* 通知正文
	 */
	Content string `json:"content,omitempty"`

	/* 通知创建时间
	 */
	CreateTime int64 `json:"createTime,omitempty"`

	/* 通知关联的悬赏分, 在问题采纳时非空
	 */
	CtoCoins int32 `json:"ctoCoins,omitempty"`

	/* 设备token
	 */
	DeviceToken string `json:"deviceToken,omitempty"`

	/* 设备类型
	 */
	DeviceType int32 `json:"deviceType,omitempty"`

	/* 邮件地址
	 */
	Email string `json:"email,omitempty"`

	/* 通知ID
	 */
	ID int64 `json:"id,omitempty"`

	/* 跳转资源ID
	 */
	LinkID int64 `json:"linkId,omitempty"`

	/* 跳转资源类型
	 */
	LinkType int32 `json:"linkType,omitempty"`

	/* 是否已读
	 */
	Read *bool `json:"read,omitempty"`

	/* 服务器当前时间
	 */
	ServerTime int64 `json:"serverTime,omitempty"`

	/* 是否创业公司员工
	 */
	Startup *bool `json:"startup,omitempty"`

	/* 通知标题
	 */
	Title string `json:"title,omitempty"`

	/* 通知类型
	 */
	Type int32 `json:"type,omitempty"`

	/* 通知的用户ID
	 */
	UserID int64 `json:"userId,omitempty"`
}

// Validate validates this notification
func (m *Notification) Validate(formats strfmt.Registry) error {
	return nil
}
