package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*表示OSS签名响应

swagger:model OssSignatureResponse
*/
type OssSignatureResponse struct {

	/* access key ID
	 */
	AccessKeyID string `json:"accessKeyId,omitempty"`

	/* policy失效时间
	 */
	ExpiresIn int64 `json:"expiresIn,omitempty"`

	/* decoded policy
	 */
	Policy string `json:"policy,omitempty"`

	/* 服务器当前时间
	 */
	ServerTime int64 `json:"serverTime,omitempty"`

	/* 签名
	 */
	Signature string `json:"signature,omitempty"`
}

// Validate validates this oss signature response
func (m *OssSignatureResponse) Validate(formats strfmt.Registry) error {
	return nil
}
