package models

import (
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
)

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*表示发布资源

swagger:model Post
*/
type Post struct {
	Resource

	/* 发布者
	 */
	Author *Author `json:"author,omitempty"`

	/* 发布内容
	 */
	Content string `json:"content,omitempty"`

	/* 发布状态
	 */
	Status int32 `json:"status,omitempty"`

	/* 发布标题
	 */
	Title string `json:"title,omitempty"`

	/* 浏览次数
	 */
	ViewCount int64 `json:"viewCount,omitempty"`
}

// Validate validates this post
func (m *Post) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.Resource.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
