package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*表示推荐资源

swagger:model Recommendation
*/
type Recommendation struct {

	/* 推荐ID
	 */
	ID int64 `json:"id,omitempty"`

	/* 推荐对象名称
	 */
	Name string `json:"name,omitempty"`

	/* Photo photo
	 */
	Photo string `json:"photo,omitempty"`

	/* 推荐对象职位
	 */
	Position string `json:"position,omitempty"`

	/* 推荐语
	 */
	Words string `json:"words,omitempty"`
}

// Validate validates this recommendation
func (m *Recommendation) Validate(formats strfmt.Registry) error {
	return nil
}
