package models

import (
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
)

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*表示回复资源

swagger:model Reply
*/
type Reply struct {
	Post

	/* 是否匿名发布
	 */
	Anonymous *bool `json:"anonymous,omitempty"`

	/* 评论数
	 */
	CommentCount int32 `json:"commentCount,omitempty"`

	/* 专家信息
	 */
	Expert Expert `json:"expert,omitempty"`

	/* 回复主题
	 */
	Topic Topic `json:"topic,omitempty"`

	/* 回复主题的ID
	 */
	TopicID int64 `json:"topicId,omitempty"`
}

// Validate validates this reply
func (m *Reply) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.Post.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
