package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*表示STS临时token响应

swagger:model StsResponse
*/
type StsResponse struct {

	/* access key ID
	 */
	AccessKeyID string `json:"accessKeyId,omitempty"`

	/* access key secret
	 */
	AccessKeySecret string `json:"accessKeySecret,omitempty"`

	/* token失效时间
	 */
	ExpiresIn int64 `json:"expiresIn,omitempty"`

	/* 服务器当前时间
	 */
	ServerTime int64 `json:"serverTime,omitempty"`

	/* token
	 */
	Token string `json:"token,omitempty"`
}

// Validate validates this sts response
func (m *StsResponse) Validate(formats strfmt.Registry) error {
	return nil
}
