package models

import (
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
)

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*表示用户资源

swagger:model User
*/
type User struct {
	Resource

	/* 用户头像
	 */
	Avatar string `json:"avatar,omitempty"`

	/* 用户介绍
	 */
	Description string `json:"description,omitempty"`

	/* 用户使用的移动设备token
	 */
	DeviceToken string `json:"deviceToken,omitempty"`

	/* 用户邮件地址
	 */
	Email string `json:"email,omitempty"`

	/* 用户姓名
	 */
	Name string `json:"name,omitempty"`

	/* 用户密码，仅在创建用户时需要提供
	 */
	Password string `json:"password,omitempty"`

	/* 用户电话号码
	 */
	Phone string `json:"phone,omitempty"`

	/* 创业公司ID
	 */
	StartupID int64 `json:"startupId,omitempty"`

	/* 浏览次数
	 */
	ViewCount int64 `json:"viewCount,omitempty"`
}

// Validate validates this user
func (m *User) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.Resource.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
