package operation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/tangr1/hicto/models"
)

type DeleteRecommendationsIDReader struct {
	formats strfmt.Registry
}

func (o *DeleteRecommendationsIDReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteRecommendationsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteRecommendationsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewDeleteRecommendationsIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteRecommendationsIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteRecommendationsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDeleteRecommendationsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteRecommendationsIDOK creates a DeleteRecommendationsIDOK with default headers values
func NewDeleteRecommendationsIDOK() *DeleteRecommendationsIDOK {
	return &DeleteRecommendationsIDOK{}
}

/*DeleteRecommendationsIDOK

成功删除推荐
*/
type DeleteRecommendationsIDOK struct {
	Payload *models.Recommendation
}

func (o *DeleteRecommendationsIDOK) Error() string {
	return fmt.Sprintf("[DELETE /recommendations/{id}/][%d] deleteRecommendationsIdOK  %+v", 200, o.Payload)
}

func (o *DeleteRecommendationsIDOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Recommendation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewDeleteRecommendationsIDBadRequest creates a DeleteRecommendationsIDBadRequest with default headers values
func NewDeleteRecommendationsIDBadRequest() *DeleteRecommendationsIDBadRequest {
	return &DeleteRecommendationsIDBadRequest{}
}

/*DeleteRecommendationsIDBadRequest

无效请求
*/
type DeleteRecommendationsIDBadRequest struct {
	Payload *models.Error
}

func (o *DeleteRecommendationsIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /recommendations/{id}/][%d] deleteRecommendationsIdBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteRecommendationsIDBadRequest) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewDeleteRecommendationsIDUnauthorized creates a DeleteRecommendationsIDUnauthorized with default headers values
func NewDeleteRecommendationsIDUnauthorized() *DeleteRecommendationsIDUnauthorized {
	return &DeleteRecommendationsIDUnauthorized{}
}

/*DeleteRecommendationsIDUnauthorized

未认证
*/
type DeleteRecommendationsIDUnauthorized struct {
	Payload *models.Error
}

func (o *DeleteRecommendationsIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /recommendations/{id}/][%d] deleteRecommendationsIdUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteRecommendationsIDUnauthorized) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewDeleteRecommendationsIDForbidden creates a DeleteRecommendationsIDForbidden with default headers values
func NewDeleteRecommendationsIDForbidden() *DeleteRecommendationsIDForbidden {
	return &DeleteRecommendationsIDForbidden{}
}

/*DeleteRecommendationsIDForbidden

无访问权限
*/
type DeleteRecommendationsIDForbidden struct {
	Payload *models.Error
}

func (o *DeleteRecommendationsIDForbidden) Error() string {
	return fmt.Sprintf("[DELETE /recommendations/{id}/][%d] deleteRecommendationsIdForbidden  %+v", 403, o.Payload)
}

func (o *DeleteRecommendationsIDForbidden) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewDeleteRecommendationsIDNotFound creates a DeleteRecommendationsIDNotFound with default headers values
func NewDeleteRecommendationsIDNotFound() *DeleteRecommendationsIDNotFound {
	return &DeleteRecommendationsIDNotFound{}
}

/*DeleteRecommendationsIDNotFound

没找到指定对象
*/
type DeleteRecommendationsIDNotFound struct {
	Payload *models.Error
}

func (o *DeleteRecommendationsIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /recommendations/{id}/][%d] deleteRecommendationsIdNotFound  %+v", 404, o.Payload)
}

func (o *DeleteRecommendationsIDNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewDeleteRecommendationsIDInternalServerError creates a DeleteRecommendationsIDInternalServerError with default headers values
func NewDeleteRecommendationsIDInternalServerError() *DeleteRecommendationsIDInternalServerError {
	return &DeleteRecommendationsIDInternalServerError{}
}

/*DeleteRecommendationsIDInternalServerError

服务端内部错误
*/
type DeleteRecommendationsIDInternalServerError struct {
	Payload *models.Error
}

func (o *DeleteRecommendationsIDInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /recommendations/{id}/][%d] deleteRecommendationsIdInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteRecommendationsIDInternalServerError) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}
