package operation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/tangr1/hicto/models"
)

type DeleteStarsIDReader struct {
	formats strfmt.Registry
}

func (o *DeleteStarsIDReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteStarsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteStarsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewDeleteStarsIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteStarsIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteStarsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDeleteStarsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteStarsIDOK creates a DeleteStarsIDOK with default headers values
func NewDeleteStarsIDOK() *DeleteStarsIDOK {
	return &DeleteStarsIDOK{}
}

/*DeleteStarsIDOK

成功删除明星
*/
type DeleteStarsIDOK struct {
	Payload *models.Star
}

func (o *DeleteStarsIDOK) Error() string {
	return fmt.Sprintf("[DELETE /stars/{id}/][%d] deleteStarsIdOK  %+v", 200, o.Payload)
}

func (o *DeleteStarsIDOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Star)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewDeleteStarsIDBadRequest creates a DeleteStarsIDBadRequest with default headers values
func NewDeleteStarsIDBadRequest() *DeleteStarsIDBadRequest {
	return &DeleteStarsIDBadRequest{}
}

/*DeleteStarsIDBadRequest

无效请求
*/
type DeleteStarsIDBadRequest struct {
	Payload *models.Error
}

func (o *DeleteStarsIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /stars/{id}/][%d] deleteStarsIdBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteStarsIDBadRequest) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewDeleteStarsIDUnauthorized creates a DeleteStarsIDUnauthorized with default headers values
func NewDeleteStarsIDUnauthorized() *DeleteStarsIDUnauthorized {
	return &DeleteStarsIDUnauthorized{}
}

/*DeleteStarsIDUnauthorized

未认证
*/
type DeleteStarsIDUnauthorized struct {
	Payload *models.Error
}

func (o *DeleteStarsIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /stars/{id}/][%d] deleteStarsIdUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteStarsIDUnauthorized) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewDeleteStarsIDForbidden creates a DeleteStarsIDForbidden with default headers values
func NewDeleteStarsIDForbidden() *DeleteStarsIDForbidden {
	return &DeleteStarsIDForbidden{}
}

/*DeleteStarsIDForbidden

无访问权限
*/
type DeleteStarsIDForbidden struct {
	Payload *models.Error
}

func (o *DeleteStarsIDForbidden) Error() string {
	return fmt.Sprintf("[DELETE /stars/{id}/][%d] deleteStarsIdForbidden  %+v", 403, o.Payload)
}

func (o *DeleteStarsIDForbidden) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewDeleteStarsIDNotFound creates a DeleteStarsIDNotFound with default headers values
func NewDeleteStarsIDNotFound() *DeleteStarsIDNotFound {
	return &DeleteStarsIDNotFound{}
}

/*DeleteStarsIDNotFound

没找到指定对象
*/
type DeleteStarsIDNotFound struct {
	Payload *models.Error
}

func (o *DeleteStarsIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /stars/{id}/][%d] deleteStarsIdNotFound  %+v", 404, o.Payload)
}

func (o *DeleteStarsIDNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewDeleteStarsIDInternalServerError creates a DeleteStarsIDInternalServerError with default headers values
func NewDeleteStarsIDInternalServerError() *DeleteStarsIDInternalServerError {
	return &DeleteStarsIDInternalServerError{}
}

/*DeleteStarsIDInternalServerError

服务端内部错误
*/
type DeleteStarsIDInternalServerError struct {
	Payload *models.Error
}

func (o *DeleteStarsIDInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /stars/{id}/][%d] deleteStarsIdInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteStarsIDInternalServerError) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}
