package operation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
	"github.com/go-swagger/go-swagger/swag"
)

// NewGetFeedbacksIDParams creates a new GetFeedbacksIDParams object
// with the default values initialized.
func NewGetFeedbacksIDParams() *GetFeedbacksIDParams {
	return &GetFeedbacksIDParams{}
}

/*GetFeedbacksIDParams contains all the parameters to send to the API endpoint
for the get feedbacks ID operation typically these are written to a http.Request
*/
type GetFeedbacksIDParams struct {

	/*ID
	  反馈ID

	*/
	ID int64
}

// WithID adds the id to the get feedbacks ID params
func (o *GetFeedbacksIDParams) WithID(id int64) *GetFeedbacksIDParams {
	o.ID = id
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetFeedbacksIDParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
