package operation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/tangr1/hicto/models"
)

type PostStarsReader struct {
	formats strfmt.Registry
}

func (o *PostStarsReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostStarsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostStarsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewPostStarsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewPostStarsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewPostStarsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostStarsCreated creates a PostStarsCreated with default headers values
func NewPostStarsCreated() *PostStarsCreated {
	return &PostStarsCreated{}
}

/*PostStarsCreated

成功创建
*/
type PostStarsCreated struct {
	Payload *models.Star
}

func (o *PostStarsCreated) Error() string {
	return fmt.Sprintf("[POST /stars/][%d] postStarsCreated  %+v", 201, o.Payload)
}

func (o *PostStarsCreated) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Star)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewPostStarsBadRequest creates a PostStarsBadRequest with default headers values
func NewPostStarsBadRequest() *PostStarsBadRequest {
	return &PostStarsBadRequest{}
}

/*PostStarsBadRequest

无效请求
*/
type PostStarsBadRequest struct {
	Payload *models.Error
}

func (o *PostStarsBadRequest) Error() string {
	return fmt.Sprintf("[POST /stars/][%d] postStarsBadRequest  %+v", 400, o.Payload)
}

func (o *PostStarsBadRequest) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewPostStarsUnauthorized creates a PostStarsUnauthorized with default headers values
func NewPostStarsUnauthorized() *PostStarsUnauthorized {
	return &PostStarsUnauthorized{}
}

/*PostStarsUnauthorized

未认证
*/
type PostStarsUnauthorized struct {
	Payload *models.Error
}

func (o *PostStarsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /stars/][%d] postStarsUnauthorized  %+v", 401, o.Payload)
}

func (o *PostStarsUnauthorized) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewPostStarsForbidden creates a PostStarsForbidden with default headers values
func NewPostStarsForbidden() *PostStarsForbidden {
	return &PostStarsForbidden{}
}

/*PostStarsForbidden

无访问权限
*/
type PostStarsForbidden struct {
	Payload *models.Error
}

func (o *PostStarsForbidden) Error() string {
	return fmt.Sprintf("[POST /stars/][%d] postStarsForbidden  %+v", 403, o.Payload)
}

func (o *PostStarsForbidden) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewPostStarsInternalServerError creates a PostStarsInternalServerError with default headers values
func NewPostStarsInternalServerError() *PostStarsInternalServerError {
	return &PostStarsInternalServerError{}
}

/*PostStarsInternalServerError

服务端内部错误
*/
type PostStarsInternalServerError struct {
	Payload *models.Error
}

func (o *PostStarsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /stars/][%d] postStarsInternalServerError  %+v", 500, o.Payload)
}

func (o *PostStarsInternalServerError) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}
