package operation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/tangr1/hicto/models"
)

type PostRecommendationsReader struct {
	formats strfmt.Registry
}

func (o *PostRecommendationsReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostRecommendationsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostRecommendationsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewPostRecommendationsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewPostRecommendationsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewPostRecommendationsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRecommendationsCreated creates a PostRecommendationsCreated with default headers values
func NewPostRecommendationsCreated() *PostRecommendationsCreated {
	return &PostRecommendationsCreated{}
}

/*PostRecommendationsCreated

成功创建
*/
type PostRecommendationsCreated struct {
	Payload *models.Recommendation
}

func (o *PostRecommendationsCreated) Error() string {
	return fmt.Sprintf("[POST /recommendations/][%d] postRecommendationsCreated  %+v", 201, o.Payload)
}

func (o *PostRecommendationsCreated) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Recommendation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewPostRecommendationsBadRequest creates a PostRecommendationsBadRequest with default headers values
func NewPostRecommendationsBadRequest() *PostRecommendationsBadRequest {
	return &PostRecommendationsBadRequest{}
}

/*PostRecommendationsBadRequest

无效请求
*/
type PostRecommendationsBadRequest struct {
	Payload *models.Error
}

func (o *PostRecommendationsBadRequest) Error() string {
	return fmt.Sprintf("[POST /recommendations/][%d] postRecommendationsBadRequest  %+v", 400, o.Payload)
}

func (o *PostRecommendationsBadRequest) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewPostRecommendationsUnauthorized creates a PostRecommendationsUnauthorized with default headers values
func NewPostRecommendationsUnauthorized() *PostRecommendationsUnauthorized {
	return &PostRecommendationsUnauthorized{}
}

/*PostRecommendationsUnauthorized

未认证
*/
type PostRecommendationsUnauthorized struct {
	Payload *models.Error
}

func (o *PostRecommendationsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /recommendations/][%d] postRecommendationsUnauthorized  %+v", 401, o.Payload)
}

func (o *PostRecommendationsUnauthorized) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewPostRecommendationsForbidden creates a PostRecommendationsForbidden with default headers values
func NewPostRecommendationsForbidden() *PostRecommendationsForbidden {
	return &PostRecommendationsForbidden{}
}

/*PostRecommendationsForbidden

无访问权限
*/
type PostRecommendationsForbidden struct {
	Payload *models.Error
}

func (o *PostRecommendationsForbidden) Error() string {
	return fmt.Sprintf("[POST /recommendations/][%d] postRecommendationsForbidden  %+v", 403, o.Payload)
}

func (o *PostRecommendationsForbidden) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewPostRecommendationsInternalServerError creates a PostRecommendationsInternalServerError with default headers values
func NewPostRecommendationsInternalServerError() *PostRecommendationsInternalServerError {
	return &PostRecommendationsInternalServerError{}
}

/*PostRecommendationsInternalServerError

服务端内部错误
*/
type PostRecommendationsInternalServerError struct {
	Payload *models.Error
}

func (o *PostRecommendationsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /recommendations/][%d] postRecommendationsInternalServerError  %+v", 500, o.Payload)
}

func (o *PostRecommendationsInternalServerError) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}
