package operation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/tangr1/hicto/models"
)

// NewPostRecommendationsParams creates a new PostRecommendationsParams object
// with the default values initialized.
func NewPostRecommendationsParams() *PostRecommendationsParams {
	return &PostRecommendationsParams{}
}

/*PostRecommendationsParams contains all the parameters to send to the API endpoint
for the post recommendations operation typically these are written to a http.Request
*/
type PostRecommendationsParams struct {

	/*Body*/
	Body *models.CreateRecommendationRequest
}

// WithBody adds the body to the post recommendations params
func (o *PostRecommendationsParams) WithBody(body *models.CreateRecommendationRequest) *PostRecommendationsParams {
	o.Body = body
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostRecommendationsParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Body == nil {
		o.Body = new(models.CreateRecommendationRequest)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
