package operation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/tangr1/hicto/models"
)

// NewPostStarsParams creates a new PostStarsParams object
// with the default values initialized.
func NewPostStarsParams() *PostStarsParams {
	return &PostStarsParams{}
}

/*PostStarsParams contains all the parameters to send to the API endpoint
for the post stars operation typically these are written to a http.Request
*/
type PostStarsParams struct {

	/*Body*/
	Body *models.CreateStarRequest
}

// WithBody adds the body to the post stars params
func (o *PostStarsParams) WithBody(body *models.CreateStarRequest) *PostStarsParams {
	o.Body = body
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostStarsParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Body == nil {
		o.Body = new(models.CreateStarRequest)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
