package operation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/tangr1/hicto/models"
)

type PostFeedbacksReader struct {
	formats strfmt.Registry
}

func (o *PostFeedbacksReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostFeedbacksCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostFeedbacksBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewPostFeedbacksUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewPostFeedbacksForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewPostFeedbacksInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostFeedbacksCreated creates a PostFeedbacksCreated with default headers values
func NewPostFeedbacksCreated() *PostFeedbacksCreated {
	return &PostFeedbacksCreated{}
}

/*PostFeedbacksCreated

成功创建
*/
type PostFeedbacksCreated struct {
	Payload *models.Feedback
}

func (o *PostFeedbacksCreated) Error() string {
	return fmt.Sprintf("[POST /feedbacks/][%d] postFeedbacksCreated  %+v", 201, o.Payload)
}

func (o *PostFeedbacksCreated) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Feedback)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewPostFeedbacksBadRequest creates a PostFeedbacksBadRequest with default headers values
func NewPostFeedbacksBadRequest() *PostFeedbacksBadRequest {
	return &PostFeedbacksBadRequest{}
}

/*PostFeedbacksBadRequest

无效请求
*/
type PostFeedbacksBadRequest struct {
	Payload *models.Error
}

func (o *PostFeedbacksBadRequest) Error() string {
	return fmt.Sprintf("[POST /feedbacks/][%d] postFeedbacksBadRequest  %+v", 400, o.Payload)
}

func (o *PostFeedbacksBadRequest) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewPostFeedbacksUnauthorized creates a PostFeedbacksUnauthorized with default headers values
func NewPostFeedbacksUnauthorized() *PostFeedbacksUnauthorized {
	return &PostFeedbacksUnauthorized{}
}

/*PostFeedbacksUnauthorized

未认证
*/
type PostFeedbacksUnauthorized struct {
	Payload *models.Error
}

func (o *PostFeedbacksUnauthorized) Error() string {
	return fmt.Sprintf("[POST /feedbacks/][%d] postFeedbacksUnauthorized  %+v", 401, o.Payload)
}

func (o *PostFeedbacksUnauthorized) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewPostFeedbacksForbidden creates a PostFeedbacksForbidden with default headers values
func NewPostFeedbacksForbidden() *PostFeedbacksForbidden {
	return &PostFeedbacksForbidden{}
}

/*PostFeedbacksForbidden

无访问权限
*/
type PostFeedbacksForbidden struct {
	Payload *models.Error
}

func (o *PostFeedbacksForbidden) Error() string {
	return fmt.Sprintf("[POST /feedbacks/][%d] postFeedbacksForbidden  %+v", 403, o.Payload)
}

func (o *PostFeedbacksForbidden) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewPostFeedbacksInternalServerError creates a PostFeedbacksInternalServerError with default headers values
func NewPostFeedbacksInternalServerError() *PostFeedbacksInternalServerError {
	return &PostFeedbacksInternalServerError{}
}

/*PostFeedbacksInternalServerError

服务端内部错误
*/
type PostFeedbacksInternalServerError struct {
	Payload *models.Error
}

func (o *PostFeedbacksInternalServerError) Error() string {
	return fmt.Sprintf("[POST /feedbacks/][%d] postFeedbacksInternalServerError  %+v", 500, o.Payload)
}

func (o *PostFeedbacksInternalServerError) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}
